# Ignore hidden macOS system files
.DS_Store
.AppleDouble
.LSOverride

# Icon files
Icon?
._*

# Thumbnails
Thumbs.db

# macOS folder attributes
.Spotlight-V100
.Trashes

# macOS metadata files
.fseventsd